---
# Tâches pour l'installation de Proxmox VE

- name: Update apt cache and upgrade system packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
  register: apt_upgrade_status
  changed_when: "'0 upgraded, 0 newly installed, 0 to remove' not in apt_upgrade_status.stdout"

- name: Add Proxmox VE repository GPG key
  ansible.builtin.apt_key:
    url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
    state: present
    keyring: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg

- name: Add Proxmox VE repository
  ansible.builtin.apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/bookworm pve-enterprise
    state: present
    filename: pve-enterprise # Changé de pve-install-repo à pve-enterprise conformément à la documentation Proxmox pour Bookworm

# Note : Pour les utilisateurs sans abonnement, ils pourraient vouloir utiliser le dépôt pve-no-subscription.
# Cela peut être ajouté comme une tâche séparée ou rendu conditionnel.
# Exemple pour sans-abonnement :
# - name: Add Proxmox VE no-subscription repository
#   ansible.builtin.apt_repository:
#     repo: http://download.proxmox.com/debian/pve bookworm pve-no-subscription
#     state: present
#     filename: pve-no-subscription

- name: Install Proxmox VE, postfix, and open-iscsi
  ansible.builtin.apt:
    name:
      - proxmox-ve
      - postfix
      - open-iscsi
    state: present
  notify:
    - Refresh proxmox-boot-tool
    - Reboot and wait for system to come back
