vms:
  - name: proxy-vm
    vmid: 801
    template: "ubuntu-2204-cloudinit-template"
    cores: 1
    memory: 1024
    disk: 10
    storage: "local-lvm"
    bridge: "vmbr0"
    ip: "167.235.118.228/26" # IP publique de la VM, pas du serveur
    gateway: "167.235.118.193" # La vraie passerelle de ton sous-réseau
    private_bridge: "vmbr1"
    private_ip: "10.0.1.1/24" 

  - name: frontend-vm
    vmid: 802
    template: "ubuntu-2204-cloudinit-template"
    cores: 2
    memory: 2048
    disk: 20
    storage: "local-lvm"
    bridge: "vmbr1"
    ip: "10.0.1.10/24"
    gateway: "10.0.1.1"

  - name: backend-vm
    vmid: 803
    template: "ubuntu-2204-cloudinit-template"
    cores: 2
    memory: 2048
    disk: 30
    storage: "local-lvm"
    bridge: "vmbr1"
    ip: "10.0.1.20/24"
    gateway: "10.0.1.1"

  - name: database-vm
    vmid: 804
    template: "ubuntu-2204-cloudinit-template"
    cores: 2
    memory: 4096
    disk: 50
    storage: "local-lvm"
    bridge: "vmbr1"
    ip: "10.0.1.30/24"
    gateway: "10.0.1.1" 