---
# Tâches pour la configuration du pont réseau

- name: Ensure /root directory exists for backups
  ansible.builtin.file:
    path: /root
    state: directory
    mode: '0700'

- name: Backup current /etc/network/interfaces
  ansible.builtin.copy:
    src: /etc/network/interfaces
    dest: "/root/interfaces.backup-{{ ansible_date_time.iso8601_basic_short }}"
    remote_src: yes
    force: yes # Écraser si une sauvegarde avec exactement le même horodatage existe d'une manière ou d'une autre
  register: backup_network_config
  changed_when: backup_network_config.changed

- name: Configure vmbr0 for Hetzner public IP using template
  ansible.builtin.template:
    src: hetzner_interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
  notify: Restart networking service
  # Nous pourrions également vouloir notifier le handler de redémarrage complet si des problèmes persistent avec un simple redémarrage du service réseau
  # notify: Reboot and wait for system to come back
