---
- name: "Cloner la VM {{ vm.name }} depuis le template {{ vm.template }}"
  command: >-
    qm clone 9000 {{ vm.vmid }} 
    --name {{ vm.name }} 
    --full 
    --storage {{ vm.storage }}
  register: clone_result
  changed_when: "'successfully created' in clone_result.stdout"

- name: "Configurer les ressources (CPU, RAM) pour {{ vm.name }}"
  command: >-
    qm set {{ vm.vmid }}
    --cores {{ vm.cores }}
    --memory {{ vm.memory }}
  when: clone_result.changed

- name: "Configurer le réseau pour {{ vm.name }} (sans pare-feu Proxmox)"
  command: >-
    qm set {{ vm.vmid }}
    --net0 virtio,bridge={{ vm.bridge }}
  when: clone_result.changed

- name: "Configurer l'IP avec Cloud-Init pour {{ vm.name }}"
  command: >-
    qm set {{ vm.vmid }}
    --ipconfig0 ip={{ vm.ip }},gw={{ vm.gateway }}
    --nameserver 1.1.1.1
    --searchdomain local
  when: vm.ip is defined and vm.gateway is defined and clone_result.changed

- name: "Redimensionner le disque pour {{ vm.name }}"
  command: "qm resize {{ vm.vmid }} scsi0 {{ vm.disk }}G"
  when: clone_result.changed

- name: "Démarrer la VM {{ vm.name }}"
  command: "qm start {{ vm.vmid }}"
  when: clone_result.changed

- name: "Pause pour laisser le temps à Cloud-Init de s'exécuter"
  pause:
    seconds: 45
  when: clone_result.changed 