---
- name: Créer un bridge interne vmbr1 sur Proxmox (Debian 12)
  hosts: proxmox
  become: true
  vars_files:
    - ../../secret_vars.yml

  vars:
    vmbr1_bridge_ports: "none"
    vmbr1_comment: "Bridge interne isolé créé par Ansible"

  tasks:
    - name: S'assurer que ifupdown2 est installé
      ansible.builtin.apt:
        name: ifupdown2
        state: present
        update_cache: yes

    - name: Vérifier si vmbr1 existe déjà (configuration et interface)
      ansible.builtin.shell: |
        ip link show vmbr1 >/dev/null 2>&1 && 
        grep -q "^auto vmbr1" /etc/network/interfaces
      register: vmbr1_check
      changed_when: false
      failed_when: false

    - name: Afficher le statut de vmbr1
      ansible.builtin.debug:
        msg: "vmbr1 est {{ (vmbr1_check.rc == 0) | ternary('déjà configuré', 'absent ou incomplet') }}"

    - name: Ajouter la configuration de vmbr1 dans /etc/network/interfaces
      ansible.builtin.blockinfile:
        path: /etc/network/interfaces
        marker: "# {mark} ANSIBLE MANAGED BLOCK vmbr1"
        block: "{{ lookup('template', 'templates/vmbr1.j2') }}"
      when: vmbr1_check.rc != 0
      register: vmbr1_config

    - name: Recharger proprement l'interface vmbr1 (sans toucher vmbr0)
      ansible.builtin.shell: |
        if ip link show vmbr1 >/dev/null 2>&1; then
          ifdown vmbr1 && ifup vmbr1
        else
          ifup vmbr1
        fi
      when: vmbr1_config.changed
      register: reload_vmbr1
      changed_when: reload_vmbr1.rc == 0

    - name: Attendre que l'interface soit prête
      ansible.builtin.pause:
        seconds: 2
      when: vmbr1_config.changed

    - name: Vérifier que vmbr1 répond aux pings
      ansible.builtin.shell: ping -c 2 -I vmbr1 {{ vmbr1_ipaddr }}
      register: ping_test
      changed_when: false
      failed_when: false
      when: vmbr1_config.changed or vmbr1_check.rc == 0

    - name: Afficher le résultat du test réseau
      ansible.builtin.debug:
        msg: "Test de connectivité vmbr1 {{ (ping_test.rc == 0) | ternary('réussi', 'échoué') }}"
      when: vmbr1_config.changed or vmbr1_check.rc == 0
