---
- name: Supprimer le bridge interne vmbr1
  hosts: proxmox
  become: true
  vars_files:
    - ../../secret_vars.yml

  tasks:
    - name: Vérifier si vmbr1 existe
      ansible.builtin.shell: ip link show vmbr1
      register: vmbr1_exists
      failed_when: false
      changed_when: false

    - name: Afficher l'état actuel
      ansible.builtin.debug:
        msg: "vmbr1 est {{ (vmbr1_exists.rc == 0) | ternary('présent et sera supprimé', 'déjà absent') }}"

    - name: Désactiver l'interface vmbr1
      ansible.builtin.command: ifdown vmbr1
      when: vmbr1_exists.rc == 0
      register: vmbr1_down
      failed_when: false

    - name: Supprimer la configuration de vmbr1 du fichier interfaces
      ansible.builtin.blockinfile:
        path: /etc/network/interfaces
        marker: "# {mark} ANSIBLE MANAGED BLOCK vmbr1"
        block: ""
        state: absent
      register: vmbr1_config_removed

    - name: Vérifier que vmbr1 est supprimé
      ansible.builtin.shell: ip link show vmbr1
      register: vmbr1_check
      failed_when: false
      changed_when: false

    - name: Supprimer l'interface si elle persiste (via ip link)
      ansible.builtin.shell: ip link delete vmbr1
      when: vmbr1_check.rc == 0
      failed_when: false
      register: vmbr1_forced_delete

    - name: Vérification finale
      ansible.builtin.shell: ip link show vmbr1
      register: vmbr1_final_check
      failed_when: false
      changed_when: false

    - name: Afficher le statut de la suppression
      ansible.builtin.debug:
        msg: "vmbr1 a été {{ (vmbr1_final_check.rc != 0) | ternary('supprimé avec succès', 'partiellement supprimé ou toujours présent (problème)') }}"

    - name: Afficher des instructions supplémentaires si la suppression a échoué
      ansible.builtin.debug:
        msg: |
          Impossible de supprimer complètement vmbr1. 
          Essayez manuellement avec:
          - ifdown vmbr1
          - ip link delete vmbr1
          - Modifiez manuellement /etc/network/interfaces
        verbosity: 0
      when: vmbr1_final_check.rc == 0
