---
- name: Créer une VM test sur vmbr1
  hosts: proxmox
  become: true
  vars_files:
    - ../../secret_vars.yml

  vars:
    vm_name: test-vmbr1
    vm_id: 999
    vm_memory: 512
    vm_cores: 1

  tasks:
    - name: S'assurer que pip est installé
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Installer les dépendances Python via apt
      ansible.builtin.apt:
        name:
          - python3-proxmoxer
          - python3-requests
        state: present
        update_cache: yes

    - name: Vérifier si vmbr1 existe
      ansible.builtin.shell: ip link show vmbr1
      register: vmbr1_exists
      failed_when: vmbr1_exists.rc != 0
      changed_when: false

    - name: Créer une VM test minimaliste
      community.general.proxmox_kvm:
        api_host: "localhost"
        api_user: "root@pam"
        api_password: "{{ proxmox_api_password }}"
        name: "{{ vm_name }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ vm_id }}"
        ostype: l26
        cores: "{{ vm_cores }}"
        memory: "{{ vm_memory }}"
        net:
          net0: "model=virtio,bridge=vmbr1"
        state: present
      register: vm_creation

    - name: Afficher des informations sur la VM créée
      ansible.builtin.debug:
        msg: "VM '{{ vm_name }}' (ID {{ vm_id }}) créée avec succès sur vmbr1"
      when: vm_creation is changed
