---
# Tâches pour les vérifications post-installation

- name: Check if PVE kernel is running
  ansible.builtin.command: uname -r
  register: kernel_output
  changed_when: false
  failed_when: "'pve' not in kernel_output.stdout"
  check_mode: no # Cette commande doit toujours s'exécuter, même en mode de vérification (check mode)

- name: Display current running kernel
  ansible.builtin.debug:
    msg: "Current kernel: {{ kernel_output.stdout }}"

- name: Wait for Proxmox web UI (port 8006) to be available
  ansible.builtin.wait_for:
    port: 8006
    host: "{{ ansible_host | default(inventory_hostname) }}" # Utiliser l'hôte de l'inventaire
    timeout: 120 # Attendre jusqu'à 2 minutes
    delay: 10 # Vérifier toutes les 10 secondes
  delegate_to: localhost # Exécuter cette vérification depuis le nœud de contrôle

- name: Get system uptime
  ansible.builtin.shell: cat /proc/uptime | awk '{print $1}'
  register: uptime_output
  changed_when: false
  check_mode: no

- name: Display system uptime
  ansible.builtin.debug:
    msg: "System uptime: {{ uptime_output.stdout }} seconds"

- name: Assert that system uptime is at least 5 minutes (300 seconds)
  ansible.builtin.assert:
    that:
      - uptime_output.stdout | float >= 300
    fail_msg: "System uptime is less than 5 minutes. Current uptime: {{ uptime_output.stdout }} seconds. The system might not be stable."
    quiet: yes

- name: Display post-installation check success message
  ansible.builtin.debug:
    msg: "Proxmox VE post-installation checks completed successfully. System is stable and Proxmox services are responding."
