---
- name: Installer Proxmox VE 8 sur Debian 12 (sans redémarrage)
  hosts: all
  gather_facts: yes
  vars_files:
    - ../secret_vars.yml
  vars:
    proxmox_hostname: pve

  tasks:
    - name: "Suppression du fichier de dépôt Proxmox Enterprise pour éviter les erreurs"
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: "Mise à jour du cache apt et mise à niveau complète"
      ansible.builtin.apt:
        update_cache: yes
        upgrade: "full"
        cache_valid_time: 3600

    - name: "Installation des dépendances (gnupg, curl)"
      ansible.builtin.apt:
        name:
          - gnupg
          - curl
        state: present

    - name: "Ajout de la clé GPG Proxmox"
      ansible.builtin.get_url:
        url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
        dest: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
        mode: '0644'


    - name: "Ajout du dépôt Proxmox No-Subscription"
      ansible.builtin.apt_repository:
        repo: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
        state: present
        filename: pve-no-subscription

    - name: "Mise à jour du cache apt après ajout des dépôts Proxmox"
      ansible.builtin.apt:
        update_cache: yes

    - name: "Pré-configuration de Postfix (Local only)"
      ansible.builtin.debconf:
        name: postfix
        question: "postfix/main_mailer_type"
        value: 'Local only'
        vtype: select

    - name: "Installation des paquets Proxmox VE, Postfix et Open-iSCSI"
      ansible.builtin.apt:
        name:
          - proxmox-ve
          - postfix
          - open-iscsi
        state: present

    - name: "Suppression du paquet os-prober"
      ansible.builtin.apt:
        name: os-prober
        state: absent

    - name: "Définition du nom d'hôte (hostname)"
      ansible.builtin.hostname:
        name: "{{ proxmox_hostname }}"

    - name: "Associer l'IPv4 publique au proxmox_hostname dans /etc/hosts"
      ansible.builtin.replace:
        path: /etc/hosts
        regexp: '^{{ ansible_default_ipv4.address }}\s+.*$'
        replace: '{{ ansible_default_ipv4.address }} {{ proxmox_hostname }}'
      when: ansible_default_ipv4.address is defined

    - name: "Associer l'IPv6 publique au proxmox_hostname dans /etc/hosts (si IPv6 configurée)"
      ansible.builtin.replace:
        path: /etc/hosts
        regexp: '^{{ ansible_default_ipv6.address }}\s+.*$'
        replace: '{{ ansible_default_ipv6.address }} {{ proxmox_hostname }}'
      when: ansible_default_ipv6.address is defined and ansible_default_ipv6.address | length > 0

    - name: "Mise à jour de /etc/hosts pour le nouveau nom d'hôte"
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1.*'
        line: "127.0.1.1 {{ proxmox_hostname }}"
        owner: root
        group: root
        mode: '0644'

    - name: "Message de reboot manuel"
      ansible.builtin.debug:
        msg: "Installation terminée. Redémarre le serveur manuellement (via reboot ou console fournisseur) avant de poursuivre."
