---
# Playbook pour l'ajout d'un bridge privé vmbr1
- hosts: proxmox
  become: yes
  gather_facts: no # Pas indispensable ici si les playbooks précédents ont déjà tourné

  vars:
    vmbr1_config_block: |
      # Pont privé pour les VMs
      auto vmbr1
      iface vmbr1 inet static
          address {{ proxmox_vmbr1_ip | default('192.168.100.1') }}/{{ proxmox_vmbr1_cidr | default('24') }}
          bridge-ports {{ proxmox_vmbr1_bridge_ports | default('none') }}
          bridge-stp off
          bridge-fd 0
          # post-up echo 1 > /proc/sys/net/ipv4/ip_forward # Activer le transfert IP si ce pont doit router

  tasks:
    - name: Add vmbr1 configuration to /etc/network/interfaces
      ansible.builtin.blockinfile:
        path: /etc/network/interfaces
        block: "{{ vmbr1_config_block }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR VMBR1"
        state: present
      notify: Restart networking service (vmbr1)

  handlers:
    - name: Restart networking service (vmbr1)
      listen: "Restart networking service (vmbr1)"
      ansible.builtin.service:
        name: networking
        state: restarted
      # Envisager un handler de redémarrage complet en cas de problèmes
      # - name: Redémarrer et attendre le retour du système (vmbr1)
      #   listen: "Redémarrer et attendre le retour du système (vmbr1)"
      #   block:
      #     - name: Redémarrer le serveur après les modifications de vmbr1
      #       ansible.builtin.reboot:
      #         reboot_timeout: 3600
      #         connect_timeout: 5
      #         test_command: whoami
      #       ignore_errors: true
      #     - name: Attendre que SSH soit disponible après le redémarrage (vmbr1)
      #       ansible.builtin.wait_for_connection:
      #         delay: 30
      #         timeout: 600
      #         sleep: 15
