---
- name: Nettoyer et supprimer les VMs Proxmox
  hosts: proxmox
  gather_facts: no
  vars_files:
    - ../secret_vars.yml # Variables de connexion Proxmox
    - ../vm_config.example.yml # Liste des VMs à supprimer

  tasks:
    - name: "Arrêter la VM {{ item.name }} (si elle existe)"
      command: "qm stop {{ item.vmid }}"
      register: stop_result
      failed_when: "'does not exist' not in stop_result.stderr and stop_result.rc != 0"
      changed_when: stop_result.rc == 0
      loop: "{{ vms }}"
      loop_control:
        loop_var: item

    - name: "Détruire la VM {{ item.name }} (si elle existe)"
      command: "qm destroy {{ item.vmid }} --purge" # L'option --purge supprime aussi les disques
      register: destroy_result
      failed_when: "'does not exist' not in destroy_result.stderr and destroy_result.rc != 0"
      changed_when: destroy_result.rc == 0
      loop: "{{ vms }}"
      loop_control:
        loop_var: item 