---
- name: Déployer VM runner-vm sur Proxmox
  hosts: localhost
  gather_facts: false
  vars:
    proxmox_api_host: "{{ proxmox_host }}"
    proxmox_api_user: "{{ proxmox_user }}@pam"
    proxmox_api_password: "{{ proxmox_password }}"
    proxmox_api_validate_certs: false
    
  tasks:
    - name: Créer/Mettre à jour la VM runner-vm
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        validate_certs: "{{ proxmox_api_validate_certs }}"
        node: pve
        vmid: 200
        name: runner-vm
        ostype: l26
        cores: 2
        memory: 2048
        scsi:
          scsi0: "local-lvm:20,format=raw"
        net:
          net0: "virtio,bridge=vmbr0"
        cdrom: "local:iso/debian-12.5.0-amd64-netinst.iso"
        boot: "order=cdrom;scsi0"
        onboot: true
        state: present
        update: true
      register: vm_result

    - name: Démarrer la VM si elle n'est pas déjà démarrée
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        validate_certs: "{{ proxmox_api_validate_certs }}"
        node: pve
        vmid: 200
        state: started
      when: vm_result.changed or vm_result.msg is defined

    - name: Message de confirmation
      debug:
        msg: "VM runner-vm (#200) prête ! Pense à monter l'ISO et installer Debian." 